In [ ]:

#install libraries that are not installed by default

!pip install pyxlsb

Collecting pyxlsb
  Downloading pyxlsb-1.0.10-py2.py3-none-any.whl.metadata (2.5 kB)
Downloading pyxlsb-1.0.10-py2.py3-none-any.whl (23 kB)
Installing collected packages: pyxlsb
Successfully installed pyxlsb-1.0.10

In [ ]:
# Import the required libraries

import pandas as pd
import pyxlsb
import numpy as np
import zipfile

In [ ]:
#After upload the data set and unzip the compressed file
with zipfile.ZipFile("User_Viewing_Behavior_Sample_data.zip", 'r') as zip_ref:
   zip_ref.extractall("temp_folder")

In [ ]:
#read the data set
file_path = "temp_folder/User_Viewing_Behavior_Sample_data.csv"
dataframe = pd.read_csv(file_path,encoding= 'latin1')

In [ ]:
# check the data shape
dataframe.shape

(1000, 16384)

In [ ]:
# display the first 5 rows
dataframe.head()

,Column1,date_,user_id_maped,program_name,duration_seconds,program_class,season,episode,program_desc,program_genre,...,Column16363,Column16364,Column16365,Column16366,Column16367,Column16368,Column16369,Column16370,Column16371,Column16372
0,1,5/27/2017,26138,100 treets,40,MOVIE,0,0,Drama Movie100 Streets,Drama,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,5/21/2017,7946,Moana,17,MOVIE,0,0,Animation MovieMoana (HD),Animation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,8/10/2017,7418,The Mermaid Princess,8,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,7/26/2017,19307,The Mermaid Princess,76,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,7/7/2017,15860,Churchill,87,MOVIE,0,0,Biography MovieChurchill (HD),Biography,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Data Preprocessing on the input data
dataframe = dataframe.drop(columns=['Column1'])         # dropping the index column
dataframe['program_name'] = dataframe['program_name'].str.strip()  # trim spaces in movies names to avoid misspellings in input data
dataframe['date_'] = pd.to_datetime(dataframe['date_'])  # read date column as date data type
dataframe[['duration_seconds', 'season','episode','series_title','hd']] = dataframe[['duration_seconds', 'season','episode','series_title','hd']].apply(pd.to_numeric)  # read numeric columns as numeric data types
dataframe[['user_id_maped', 'program_name','program_class','program_desc','program_genre','original_name']] = dataframe[['user_id_maped', 'program_name','program_class','program_desc','program_genre','original_name']].astype(str) # read string columns as string data types

In [ ]:
# display the dataset after applying data types
dataframe.head()

,date_,user_id_maped,program_name,duration_seconds,program_class,season,episode,program_desc,program_genre,series_title,...,Column16363,Column16364,Column16365,Column16366,Column16367,Column16368,Column16369,Column16370,Column16371,Column16372
0,2017-05-27,26138,100 treets,40,MOVIE,0,0,Drama Movie100 Streets,Drama,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-05-21,7946,Moana,17,MOVIE,0,0,Animation MovieMoana (HD),Animation,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-08-10,7418,The Mermaid Princess,8,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-07-26,19307,The Mermaid Princess,76,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-07-07,15860,Churchill,87,MOVIE,0,0,Biography MovieChurchill (HD),Biography,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# describe the numeric values in the dataset
dataframe.describe()

,date_,duration_seconds,season,episode,series_title,hd,Column2,Column3,Column4,Column5,...,Column16363,Column16364,Column16365,Column16366,Column16367,Column16368,Column16369,Column16370,Column16371,Column16372
count,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2017-09-16 04:26:24,963.516000,0.436000,1.405000,0.007000,0.684000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2017-03-14 00:00:00,2.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2017-05-25 00:00:00,23.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2017-09-03 00:00:00,74.000000,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2018-01-06 00:00:00,102.000000,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2018-04-30 00:00:00,388356.000000,10.000000,49.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,12393.083191,1.351196,4.690093,0.083414,0.465146,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# check if any column has null value in the dataset
dataframe.isnull().any()

date_               False
user_id_maped       False
program_name        False
duration_seconds    False
program_class       False
                    ...
Column16368          True
Column16369          True
Column16370          True
Column16371          True
Column16372          True
Length: 16383, dtype: bool

In [ ]:
#make a Copy of the data frame
df = dataframe.copy()

In [ ]:
# try to get the most watched movies (Total Views / Total Users Views / Total watch time)
# For series concatenated the Session episode to differentiate between episodes
grouped=df.copy()
grouped.loc[grouped['program_class'] == 'SERIES/EPISODES', 'program_name'] = grouped['program_name']+'_SE'+grouped['season'].astype(str)+'_EP'+grouped['episode'].astype(str)
grouped = grouped.groupby(['program_name','program_class'])\
.agg({'user_id_maped': [('co1', 'nunique'),('co2', 'count')],\
      'duration_seconds': [('co3', 'sum')] }).reset_index()
grouped.columns = ['program_name','program_class','No of Users who Watched', 'No of watches', 'Total watch time in seconds']
grouped['Total watch time in houres']=grouped['Total watch time in seconds']/3600
grouped = grouped.drop(columns=['Total watch time in seconds'])
grouped = grouped.sort_values(by=['Total watch time in houres', 'No of watches','No of Users who Watched'], ascending=False).reset_index(drop=True)

# show the result
grouped.head(35)

,program_name,program_class,No of Users who Watched,No of watches,Total watch time in houres
0,Ferdinand,MOVIE,18,19,108.124167
1,The Boss Baby,MOVIE,53,63,13.403056
2,The Mermaid Princess,MOVIE,31,35,12.270833
3,Finding Forrester,MOVIE,3,3,5.190000
4,The Amazing pider-Man,MOVIE,4,4,3.113611
5,Justified A Murder Of Crowes_SE5_EP1,SERIES/EPISODES,1,1,2.966944
6,Parker,MOVIE,3,3,2.609722
7,Lights Out,MOVIE,1,1,2.478333
8,Assassin's Creed,MOVIE,10,12,2.443333
9,The Patriot,MOVIE,2,2,2.315833
10,Gladiator,MOVIE,1,1,2.280000
11,Allied,MOVIE,3,3,2.262500
12,The Grey,MOVIE,3,3,2.218056
13,Robin Hood,MOVIE,2,2,2.193333
14,The Holiday,MOVIE,1,1,2.151389
15,Baywatch,MOVIE,19,21,2.098333
16,The Family Man,MOVIE,1,1,2.065000
17,Geostorm,MOVIE,9,11,1.970556
18,Dunkirk,MOVIE,10,12,1.952222
19,Rings,MOVIE,7,8,1.914722
20,How Do You Know,MOVIE,1,1,1.897500
21,Billy Lynns Long Halftime Walk,MOVIE,5,6,1.876111
22,Glory Road,MOVIE,1,1,1.758611
23,Big Mommas: Like Father Like on,MOVIE,1,1,1.711389
24,Going in tyle,MOVIE,10,13,1.710556
25,Jumanji,MOVIE,1,1,1.640278
26,The ocial Network,MOVIE,2,2,1.613889
27,Drive Angry,MOVIE,2,3,1.600556
28,Paranormal Activity,MOVIE,2,2,1.598889
29,The Lego Movie,MOVIE,1,1,1.560000
30,Carrie,MOVIE,1,1,1.434444
31,The Walking Dead Tell It To The Frogs_SE1_EP3,SERIES/EPISODES,1,1,1.373056
32,Snowden,MOVIE,1,1,1.338333
33,Puss in Boots,MOVIE,2,2,1.299167
34,Easy A,MOVIE,1,1,1.216389

In [ ]:

# Use the same group by  before, but add complete background information about each program (hd,program_desc,program_genre).


grouped = df.copy()

grouped.loc[grouped['program_class'] == 'SERIES/EPISODES', 'program_name'] = (
    grouped['program_name'] + '_SE' + grouped['season'].astype(str) + '_EP' + grouped['episode'].astype(str)
)

grouped = grouped.groupby(['program_name','program_class']).agg({
    'user_id_maped': [('co1', 'nunique'), ('co2', 'count')],
    'duration_seconds': [('co3', 'sum')],
    'hd': [('hd', 'max')],
    'program_desc': [('program_desc', 'first')],
    'program_genre': [('program_genre', 'first')]
}).reset_index()

grouped.columns = [
    'program_name','program_class',
    'No of Users who Watched', 'No of watches',
    'Total watch time in seconds', 'hd',
    'program_desc', 'program_genre'
]

grouped['Total watch time in houres'] = grouped['Total watch time in seconds'] / 3600
grouped = grouped.drop(columns=['Total watch time in seconds'])

grouped = grouped.sort_values(
    by=['Total watch time in houres', 'No of watches','No of Users who Watched'],
    ascending=False
).reset_index(drop=True)

# show the result
grouped.head(35)

,program_name,program_class,No of Users who Watched,No of watches,hd,program_desc,program_genre,Total watch time in houres
0,Ferdinand,MOVIE,18,19,1,Animation MovieFerdinand (HD),Animation,108.124167
1,The Boss Baby,MOVIE,53,63,1,Animation MovieThe Boss Baby (HD),Animation,13.403056
2,The Mermaid Princess,MOVIE,31,35,1,Animation MovieThe Mermaid Princess (HD),Animation,12.270833
3,Finding Forrester,MOVIE,3,3,1,Drama MovieFinding Forrester (HD),Drama,5.190000
4,The Amazing pider-Man,MOVIE,4,4,1,Action MovieThe Amazing Spider-Man,Action,3.113611
5,Justified A Murder Of Crowes_SE5_EP1,SERIES/EPISODES,1,1,0,Action MovieA Murder Of Crowes (HD),Action,2.966944
6,Parker,MOVIE,3,3,1,Action MovieParker (HD),Action,2.609722
7,Lights Out,MOVIE,1,1,1,Horror MovieLights Out (HD),Horror,2.478333
8,Assassin's Creed,MOVIE,10,12,1,Action MovieAssassin's Creed (HD),Action,2.443333
9,The Patriot,MOVIE,2,2,1,Action MovieThe Patriot,Action,2.315833
10,Gladiator,MOVIE,1,1,1,Drama MovieGladiator (HD),Drama,2.280000
11,Allied,MOVIE,3,3,1,Action MovieAllied (HD),Action,2.262500
12,The Grey,MOVIE,3,3,0,Thriller MovieThe Grey,Thriller,2.218056
13,Robin Hood,MOVIE,2,2,1,Action MovieRobin Hood (HD),Action,2.193333
14,The Holiday,MOVIE,1,1,1,Comedy MovieThe Holiday (HD),Comedy,2.151389
15,Baywatch,MOVIE,19,21,1,Comedy MovieBaywatch (HD),Comedy,2.098333
16,The Family Man,MOVIE,1,1,1,Comedy MovieThe Family Man (HD),Comedy,2.065000
17,Geostorm,MOVIE,9,11,1,Action MovieGeostorm (HD),Action,1.970556
18,Dunkirk,MOVIE,10,12,1,nan,NOT_DEFINED_IN_UMS,1.952222
19,Rings,MOVIE,7,8,1,Horror MovieRings (HD),Horror,1.914722
20,How Do You Know,MOVIE,1,1,1,Comedy MovieHow Do You Know (HD),Comedy,1.897500
21,Billy Lynns Long Halftime Walk,MOVIE,5,6,1,nan,Drama,1.876111
22,Glory Road,MOVIE,1,1,0,Drama MovieGlory Road,Drama,1.758611
23,Big Mommas: Like Father Like on,MOVIE,1,1,0,"Comedy MovieBig Mommas: Like Father, Like Son",Comedy,1.711389
24,Going in tyle,MOVIE,10,13,1,Comedy MovieGoing in Style (HD),Comedy,1.710556
25,Jumanji,MOVIE,1,1,0,Action MovieJumanji,Action,1.640278
26,The ocial Network,MOVIE,2,2,0,Drama MovieThe Social Network,Drama,1.613889
27,Drive Angry,MOVIE,2,3,1,Thriller MovieDrive Angry (HD),Thriller,1.600556
28,Paranormal Activity,MOVIE,2,2,0,Horror MovieParanormal Activity 4,Horror,1.598889
29,The Lego Movie,MOVIE,1,1,1,Animation MovieThe Lego Movie (HD),Animation,1.560000
30,Carrie,MOVIE,1,1,1,Horror MovieCarrie (HD),Horror,1.434444
31,The Walking Dead Tell It To The Frogs_SE1_EP3,SERIES/EPISODES,1,1,0,Horror MovieTell It To The Frogs (HD),Horror,1.373056
32,Snowden,MOVIE,1,1,1,Drama MovieSnowden (HD),Drama,1.338333
33,Puss in Boots,MOVIE,2,2,0,Animation MoviePuss in Boots,Animation,1.299167
34,Easy A,MOVIE,1,1,1,Comedy MovieEasy A (HD),Comedy,1.216389

In [ ]:
#To download the results as Excel file
with pd.ExcelWriter('Sample_Results.xlsx') as writer:
      grouped.to_excel(writer, sheet_name='HD_NotHD_MOVIE_SERIES_EPISODES', index=False)